---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hwinfo.vurt.inc
  resources:
  - ghws
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hwinfo.vurt.inc
  resources:
  - ghws/finalizers
  verbs:
  - update
- apiGroups:
  - hwinfo.vurt.inc
  resources:
  - ghws/status
  verbs:
  - get
  - patch
  - update
